### ISSUE TITLE
Problem building cscore with Raspbian Stretch (Pi 3)

### ISSUE THREAD

**Issue by rtrahms** [wpilibsuite/cameraserver#102]
Hi all -
Background: building a RPi vision processor for use with our Roborio.  Using Raspbian stretch.
Have successfully build and published wpiutil and ntcore, would like to also build cscore.
Currently have OpenCV 2.4.13 build and installed.

When I start the build, the following occurs:

pi@raspberrypi:~/cscore ./gradlew -PreleaseBuild -PskipAllTests build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'cscore'.
> Exception thrown while executing model rule: DependencyConfigRules#setupDependencyDownloads(ModelMap<Task>, DependencyConfigSpec, BinaryContainer, ProjectLayout, BuildConfigSpec)
   > Could not resolve all files for configuration ':nativeDeps'.
      > Could not find opencv-cpp-linuxarm.zip (org.opencv:opencv-cpp:3.2.0).
        Searched in the following locations:
            http://first.wpi.edu/FRC/roborio/maven/development/org/opencv/opencv-cpp/3.2.0/opencv-cpp-3.2.0-linuxarm.zip
      > Could not find wpiutil-cpp-linuxarm.zip (edu.wpi.first.wpiutil:wpiutil-cpp:3.424242.0.0-beta-2-20171111160242-4-g3e4e526).
        Searched in the following locations:
            file:/home/pi/releases/maven/development/edu/wpi/first/wpiutil/wpiutil-cpp/3.424242.0.0-beta-2-20171111160242-4-g3e4e526/wpiutil-cpp-3.424242.0.0-beta-2-20171111160242-4-g3e4e526-linuxarm.zip

Any pointers?   Do I need OpenCV 3 for cscore?  What other dependencies?

Thanks,
Rob

**Comment by ThadHouse** [comment]
Is your final goal to run java or c++? If java, you will definitely need 3.2.0, and getting a proper build of opencv for that still needs some work on our end. If c++ we are actually working on a cmake build system that works with preinstalled opencv. I'll have that working tonight and could then send it.

**Comment by rtrahms** [comment]
If we were building for Roborio we would be using java, but RPi we're using c++.

**Comment by ThadHouse** [comment]
Ok. For c++ on the pi the cmake build will work just fine. I'll get a bit more docs and post a reply to this tonight.

**Comment by ThadHouse** [comment]
@rtrahms 

https://github.com/ThadHouse/CmakeWpilib/tree/visionTestPackage

Here is a repo for you to try if you would like. It should just work with the opencv you built on the pi, but note that opencv < 3.2 has never been tested. But it should, and I would be interested in hearing. Note it includes a copy of the CameraServer API from wpilib, so if you want everything published it should just work. You'll need to set your team number in main.cpp, and probably change the AddAxisCamera call to AddUsbCamera, but other then that everything should just work properly.

**Comment by virtuald** [comment]
I don't believe cscore would compile against opencv < 3.0

**Comment by rtrahms** [comment]
@ThadHouse 
I cloned the repo above, had some cmake/make issues not related to the camera_server stuff - more on no make rules for wpiutil.

**Comment by ThadHouse** [comment]
Hmm. You cloned the visionTestPackage branch, right? It worked on my windows desktop, and another person tested it on a TK1 and it worked. Thats weird you were getting errors. If you don't have it working later today, tomorrow I'll try installing Stretch on my Pi and try it out directly there.

**Comment by rtrahms** [comment]
pi@raspberrypi:~ $ git clone https://github.com/ThadHouse/CmakeWpilib -b visionTestPackage
Cloning into 'CmakeWpilib'...
remote: Counting objects: 76, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 76 (delta 26), reused 72 (delta 22), pack-reused 0
Unpacking objects: 100% (76/76), done.
pi@raspberrypi:~ $ cd CmakeWpilib/
pi@raspberrypi:~/CmakeWpilib $ dir
CMakeLists.txt	cscore_main.cpp  include  libraries  ntcore_main.cpp  src  wpiutil_main.cpp
pi@raspberrypi:~/CmakeWpilib $ cmake .
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
You have called ADD_LIBRARY for library wpiutil without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library ntcore without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library cscore without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
CMake Error: Cannot determine link language for target "wpiutil".
CMake Error: CMake can not determine linker language for target: wpiutil
CMake Error: Cannot determine link language for target "ntcore".
CMake Error: CMake can not determine linker language for target: ntcore
-- Generating done
-- Build files have been written to: /home/pi/CmakeWpilib
pi@raspberrypi:~/CmakeWpilib $ 


Am I missing something?
Rob

**Comment by ThadHouse** [comment]
Ohhh. You need to clone the submodules as well. 

git submodule update --init --recursive

**Comment by rtrahms** [comment]
Much further, thanks!
Made it through most of the build this time, failed right toward the end during cscore library build:

[ 96%] Built target cscore
[ 97%] Building CXX object CMakeFiles/camera_vision.dir/src/CameraServer.cpp.o
/home/pi/CmakeWpilib/src/CameraServer.cpp: In member function ‘cs::UsbCamera frc::CameraServer::StartAutomaticCapture()’:
/home/pi/CmakeWpilib/src/CameraServer.cpp:495:14: error: ‘HALUsageReporting’ has not been declared
   HAL_Report(HALUsageReporting::kResourceType_PCVideoServer,
              ^~~~~~~~~~~~~~~~~
/home/pi/CmakeWpilib/src/CameraServer.cpp:496:32: error: ‘HAL_Report’ was not declared in this scope
              camera.GetHandle());
                                ^
/home/pi/CmakeWpilib/src/CameraServer.cpp: In member function ‘cs::UsbCamera frc::CameraServer::StartAutomaticCapture(int)’:
/home/pi/CmakeWpilib/src/CameraServer.cpp:507:14: error: ‘HALUsageReporting’ has not been declared
   HAL_Report(HALUsageReporting::kResourceType_PCVideoServer,
              ^~~~~~~~~~~~~~~~~
/home/pi/CmakeWpilib/src/CameraServer.cpp:508:32: error: ‘HAL_Report’ was not declared in this scope
              camera.GetHandle());
                                ^
/home/pi/CmakeWpilib/src/CameraServer.cpp: In member function ‘cs::UsbCamera frc::CameraServer::StartAutomaticCapture(llvm::StringRef, int)’:
/home/pi/CmakeWpilib/src/CameraServer.cpp:516:14: error: ‘HALUsageReporting’ has not been declared
   HAL_Report(HALUsageReporting::kResourceType_PCVideoServer,
              ^~~~~~~~~~~~~~~~~
/home/pi/CmakeWpilib/src/CameraServer.cpp:517:32: error: ‘HAL_Report’ was not declared in this scope
              camera.GetHandle());
                                ^
/home/pi/CmakeWpilib/src/CameraServer.cpp: In member function ‘cs::UsbCamera frc::CameraServer::StartAutomaticCapture(llvm::StringRef, llvm::StringRef)’:
/home/pi/CmakeWpilib/src/CameraServer.cpp:525:14: error: ‘HALUsageReporting’ has not been declared
   HAL_Report(HALUsageReporting::kResourceType_PCVideoServer,
              ^~~~~~~~~~~~~~~~~
/home/pi/CmakeWpilib/src/CameraServer.cpp:526:32: error: ‘HAL_Report’ was not declared in this scope
              camera.GetHandle());
                                ^
CMakeFiles/camera_vision.dir/build.make:62: recipe for target 'CMakeFiles/camera_vision.dir/src/CameraServer.cpp.o' failed
make[2]: *** [CMakeFiles/camera_vision.dir/src/CameraServer.cpp.o] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/camera_vision.dir/all' failed
make[1]: *** [CMakeFiles/camera_vision.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/CmakeWpilib $ 


Looking to see where HALUsageReporting is defined...

**Comment by ThadHouse** [comment]
Hmm I thought I removed all of those. Just remove them. Its defined in wpilib, and not that project.

**Comment by rtrahms** [comment]
Success!  Snippet of the last part of the build...

Scanning dependencies of target camera_vision
[ 97%] Building CXX object CMakeFiles/camera_vision.dir/src/CameraServer.cpp.o
[ 98%] Building CXX object CMakeFiles/camera_vision.dir/src/main.cpp.o
[100%] Linking CXX executable camera_vision
[100%] Built target camera_vision

I built the usbcvstream example successfully as well, and also ran it successfully.  Not sure where the video is going yet, but it is reporting frames captured and the camera is active.

Snippet from my Makefile for that:

all:	usbcvstream

clean:
	rm -f usbcvstream

INCLUDE_DIRS = -I /home/pi/ntcore/src/main/native/include -I /home/pi/wpiutil/src/main/native/include -I/home/pi/CmakeWpilib/libraries/cscore/cscore/src/main/native/include
LIB_DIRS = -L /home/pi/ntcore/build/libs/ntcore/shared -L /home/pi/wpiutil/build/libs/wpiutil/shared -L/home/pi/CmakeWpilib/libraries/cscore

...
usbcvstream: usbcvstream.cpp
	g++ -o usbcvstream usbcvstream.cpp $(INCLUDE_DIRS) `pkg-config opencv --cflags --libs` -std=gnu++11  $(LIB_DIRS) -lwpiutil -lntcore -lcscore -lv4l2

**Comment by ThadHouse** [comment]
Sweet. Note that the main example provided with a change to switch to USB cameras should stream images as well. 

If you are trying to use usbcvstream, it will output the original image on `ipaddr:8081`, and the modified image on `ipaddr:8082`. If using the example in camera_vision, it will stream to `ipaddr:1181` and modified image (the bgr to hsv conversion in the main loop` to `ipaddr:1182`

**Comment by rtrahms** [comment]
I am seeing the CV page with images locally on the RPi at http://localhost:8081/.  Playing around with it, everything seems to be working well!  Thanks for the help - RPi/OpenCV2 works great with this - confirmed.

**Comment by ThadHouse** [comment]
Cool!. Note I do recommend using the main one, and not the usbcvstream. It will post all the data correctly to NetworkTables, and allow all the dashboards to properly connect to the stream. It's already set up to do the same things as the usbcvstream anyway.

**Comment by PeterJohnson** [comment]
This is fixed with wpilibsuite/allwpilib#1015, which brings cmake builds to the merged wpilib repository.
