### ISSUE TITLE
Compression in MjpegServer cannot be set programmatically

### ISSUE THREAD

**Issue by prensing** [wpilibsuite/cameraserver#106]
MjpegServer has an internal parameter "m_compression" which sets the JPEG compression. This parameter cannot be set anywhere via a program. The only method is to make an HTTP request to set it, which is not really feasible.
This parameter should be exposed for setting.

**Comment by PeterJohnson** [comment]
The compression setting can be different for every client.  Are you saying we should provide a way to set the *default* compression setting if the client doesn't specify it in HTTP parameters?

**Comment by prensing** [comment]
Yes. Right now, the Server sets it to 80, but there is *no* way to change that in the program. The client has to send an HTTP GET with the compression. If you just fetch the stream (ie just browse to "http://localhost:1181" for example), you will get the default compression, and could easily swamp your network pipe. 

Also, setting the compression using the HTTP parameter is pretty obscure. I only found it by reading the C code. Is it documented? I am just getting into cscore, but maybe I missed it, but I did not find it through Google.

**Comment by PeterJohnson** [comment]
All of the dashboards do it, and it's the approach used for the Axis camera as well.  But, no, it's not documented anywhere.

I agree it's a good feature, but I'll need to think about how to expose it.  Currently properties exist only on sources, not on sinks, so it means adding a whole infrastructure for sink properties.  Of course this may be useful in other ways though too.

**Comment by PeterJohnson** [comment]
Fixed in wpilibsuite/allwpilib#1229.
