### ISSUE TITLE
LLVM Headers missing

### ISSUE THREAD

**Issue by rdfong** [wpilibsuite/cameraserver#114]
Hi, 
Sorry if this is a noob question. Im trying to compile the usbcvstream program for my camera running on a nanopi. It looks like I'm missing LLVM headers (like raw_ostream) which wasn't listed in the required packages in the README. Should these have been installed with one of those or do I actually need them at all? In addition if I'm already using GCC why do I even need this headers, aren't they associated with Clang which is a different compiler altogether?

Thanks!

**Comment by rdfong** [comment]
For reference I already did a sudo apt-get install llvm, to no avail.

**Comment by ThadHouse** [comment]
Cscore depends on the wpiutul library. That can be found at GitHub com/wpilibsuite/wpiutil.

**Comment by rdfong** [comment]
Ahh I see, it has all those headers. Looks like I had missed an upper case letter in my path to the include folder and all my libs were out of order :/, closing.

Thanks! Now everything works but the stream is completely black, though the output says I'm getting frames.
I dont want to trouble you too much to actually help me debug stuff but do you have any ideas or tools that you can recommend that would be helpful to start?

i'm getting the output:

got frame at time 15131928926223238 size [320 x 240]
got frame at time 15131928927023199 size [320 x 240]
got frame at time 15131928927823120 size [320 x 240]
got frame at time 15131928928623107 size [320 x 240]
got frame at time 15131928929423098 size [320 x 240]
got frame at time 15131928930222989 size [320 x 240]
got frame at time 15131928931022961 size [320 x 240]

**Comment by rdfong** [comment]
To confirm, I've used the mjpg streamer tool before and have confirmed that my camera can output reasonable images with default camera settings.

**Comment by virtuald** [comment]
If you browse to the cscore webpage for the stream, there's a bunch of tuning controls you can use. Perhaps the brightness/exposure needs to be fixed.

**Comment by PeterJohnson** [comment]
What kind of camera?  Also, what web browser are you using to view the stream?

**Comment by rdfong** [comment]
It's an FA CAM-202. 
http://www.friendlyarm.com/index.php?route=product/product&product_id=90

On second thought I just tried two tests, 
a) Writing a solid color to the streaming output. This works so the actual streaming seems to be fine.

b) Writing out the captured image in usbcvstream.cpp to a file using cv::imwrite. I get a black image here. Perhaps the camera doesn't play nicely with the sink. 
Oh! I should probably be using the device name for the camera shouldn't I? Not just "usbcam" but more like "/dev/video0"

I've tried both on chrome and firefox, but since the solid color output is working I'm guessing that's not the issue.

**Comment by rdfong** [comment]
Ah oops,  I missed this guy:
CS: ERROR: ioctl VIDIOC_G_EXT_CTRLS failed at UsbCameraProperty.cpp:33: Input/output error (UsbUtil.cpp:159)

Which occurs right at the beginning when I run the executable, any idea what this could be referring to? Thanks again!

**Comment by rdfong** [comment]
Everything works fine if I use OpenCV's videowriter to capture the frames, so it looks like it's just the cvSink that's messing up somewhere. Ideally though I'd like everything to be using CSCore since it has much better support for managing camera settings. 

Maybe I can do something like set the camera settings via CSCore, then release the camera object, then use video writer to capture the frames after the settings have been set. Though I'm sure using the sink class has some kind of benefits in terms of performance as well.

**Comment by rdfong** [comment]
I exposed a method to disconnect the camera, so I now use CSCore to stream and set initial settings, but I use OpenCV directly to capture frames. Seems to work nicely.

**Comment by PeterJohnson** [comment]
The first parameter to the constructor is just a name; the second parameter is the actual connection location; if you pass 0 it uses /dev/video0. The EXT_CTRLS error means it’s having trouble enumerating the settings.  Most likely the issue is that the camera doesn’t support the image format requested.  Can you try compiling and running  https://github.com/wpilibsuite/cscore/blob/master/examples/enum_usb/enum_usb.cpp and posting the output?

**Comment by rdfong** [comment]
0: /dev/video0 (HC 3358+2100)
Properties:
CS: usbcam: Connect to USB camera on 1
CS: ERROR: ioctl VIDIOC_G_EXT_CTRLS failed at UsbCameraProperty.cpp:33: Input/output error (UsbUtil.cpp:159)
CS: WARNING: usbcam: failed to get property exposure_auto_priority (UsbCameraImpl.cpp:929)
CS: usbcam: set format 1 res 1600x1200
  raw_brightness (int): value=0 min=-127 max=127 step=1 default=0
  brightness (int): value=50 min=0 max=100 step=1 default=50
  raw_contrast (int): value=64 min=0 max=127 step=1 default=64
  contrast (int): value=50 min=0 max=100 step=1 default=50
  raw_saturation (int): value=64 min=0 max=255 step=1 default=64
  saturation (int): value=25 min=0 max=100 step=1 default=25
  raw_hue (int): value=0 min=-16000 max=16000 step=1 default=0
  hue (int): value=50 min=0 max=100 step=1 default=50
  white_balance_temperature_auto (bool): value=1 default=1
  gamma (int): value=100 min=16 max=500 step=1 default=100
  power_line_frequency (enum): value=1
    0: Disabled
    1: 50 Hz
    2: 60 Hz
  white_balance_temperature (int): value=5200 min=2800 max=6500 step=1 default=5200
  raw_sharpness (int): value=4 min=0 max=31 step=1 default=4
  sharpness (int): value=12 min=0 max=100 step=1 default=12
  exposure_auto (enum): value=3
    1: Manual Mode
    3: Aperture Priority Mode
  raw_exposure_absolute (int): value=625 min=1 max=5000 step=1 default=625
  exposure_absolute (int): value=12 min=0 max=100 step=1 default=12
  exposure_auto_priority (bool): value=0 default=0
Video Modes:
  PixelFormat:YUYV Width:1600 Height:1200 FPS:7
  PixelFormat:YUYV Width:640 Height:480 FPS:30
  PixelFormat:YUYV Width:800 Height:600 FPS:20
  PixelFormat:YUYV Width:1280 Height:720 FPS:11
  PixelFormat:YUYV Width:352 Height:288 FPS:30
  PixelFormat:YUYV Width:320 Height:240 FPS:30
  PixelFormat:YUYV Width:640 Height:480 FPS:30


Also I did already try setting video mode to kYUYV instead of kMJPEG though that did not seem to change my results.

**Comment by PeterJohnson** [comment]
There is definitely a bug with how the default video mode is selected for cameras that don't support any MJPEG formats, but if you tried using SetVideoMode() with kYUYV that should fix that.  Could you try a tweaked version of the usbstream.cpp example for camera=0 and kYUYV? (like the below)
```
int main() {
  cs::UsbCamera camera{"usbcam", 0};
  camera.SetVideoMode(cs::VideoMode::kYUYV, 320, 240, 30);
  cs::MjpegServer mjpegServer{"httpserver", 8081};
  mjpegServer.SetSource(camera);

  std::getchar();
}
```
