### ISSUE TITLE
VideoSource.getActualDataRate() throwing Video Exception

### ISSUE THREAD

**Issue by t3pfaffe** [wpilibsuite/cameraserver#129]
In Java11, Win64: 

Yes, I have telemetry on with `CameraServerJNI.setTelemetryPeriod(.5);` and I can verify that it is by successfully utilizing `VideoSource.getActualFPS()`. Is there a separate thing I am missing or have I stumbled across a bug?

**Comment by PeterJohnson** [comment]
They are generated in the same place (e.g. follow essentially the same code paths).  You will get an exception generated for either of those functions if the camera hasn't connected yet or hasn't generated any frames.

**Comment by t3pfaffe** [comment]
That is my point @PeterJohnson . The  camera is connected and getting frames. I can successfully call getActualFPS(). It works and returns the FPS. Its just getActualDataRate() that throws the exception.

**Comment by PeterJohnson** [comment]
I can't reproduce that behavior.  Are you calling the getter functions from the telemetry notification? e.g. something like:
```
    listener = new VideoListener(e -> {
      System.out.println("FPS = " + camera.getActualFPS() + " MBPS = " + (camera.getActualDataRate() / 1000000.0));
    }, VideoEvent.Kind.kTelemetryUpdated.getValue(), false);
    CameraServerJNI.setTelemetryPeriod(1.0);
```

**Comment by t3pfaffe** [comment]
This did appear to be some sort of JavaFX problem. Irrelevant towards this repo fortunately. You can close this one. My apologies.
