### ISSUE TITLE
EnumerateSourceProperties need a free function in C

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/cameraserver#2]
https://github.com/wpilibsuite/cameraserver/blob/master/include/cameraserver_c.h#L103

Allocates using malloc, so needs an associated free function

**Comment by PeterJohnson** [comment]
`CS_FreeEnumeratedProperties` already exists?

**Comment by ThadHouse** [comment]
That works. Thought they were different array types for some reason.
