### ISSUE TITLE
Getting build errors in Image.h related to vector definition in default_init_allocator.h

### ISSUE THREAD

**Issue by RichLewis007** [wpilibsuite/cameraserver#63]
I'm seeing the following build error after executing this build command in macOS on both the HEAD and v1.0.2 tag release:
```
./gradlew build -PskipArm

/Users/rich/github/cscore/src/Image.h:35:9: error: no matching constructor for initialization of 'std::vector<uchar>' (aka 'vector<unsigned char>')
      : m_data{capacity, default_init_allocator<uchar>{}} {
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:505:5: note: candidate constructor not viable: no known conversion from 'default_init_allocator<uchar>' (aka 'default_init_allocator<unsigned char>') to 'const value_type' (aka 'const unsigned char') for 2nd argument
    vector(size_type __n, const_reference __x); ...
```
I see that in the included file default_init_allocator.h some problem related to vectors looks to have been solved using the included StackOverflow discussion linked in the comments of the source code:
```
// From: http://stackoverflow.com/questions/21028299/is-this-behavior-of-vectorresizesize-type-n-under-c11-and-boost-container
// Credits: Casey and Howard Hinnant
```
Is the error that I'm seeing related to this solution not working?

**Comment by RichLewis007** [comment]
The source code line triggering the build error is line 35 of Image.h:
```
  explicit Image(std::size_t capacity)
      : m_data{capacity, default_init_allocator<uchar>{}} {
    m_data.resize(0);
  }
```

**Comment by PeterJohnson** [comment]
What compiler are you using?  While this approach optimizes performance (important on embedded systems), it's almost certainly not necessary for desktops.  There's a workaround a few lines above for MSVC (which has a similar issue compiling this code) using `#ifdef _WIN32` but it could easily be more broadly applied based on the compiler or compiler version in use.

**Comment by RichLewis007** [comment]
I'm using XCode in the latest macOS. It doesn't look like this code has been tested for building on macOS - I'll make some changes and do a pull request. It should be able to build and run on a desktop just as it does on an embedded system, right?

**Comment by virtuald** [comment]
The python package `robotpy-cscore` compiles and runs on OSX (but it uses its own build system), so you should be able to fix it to work without changing source code I suspect... though, I think my build system prefers C++14 if it finds support for that.

**Comment by TaylerUva** [comment]
I am having the same issue. Has a fix been created yet or is at least in the works?

**Comment by PeterJohnson** [comment]
A fix is in the works.

**Comment by TaylerUva** [comment]
Running ./gradlew build -PskipAthena with the latest build seems to fix the issue for me.

**Comment by PeterJohnson** [comment]
This has been fixed; the code that caused an issue on Mac is now conditionally compiled so it is used only on Linux.
