### ISSUE TITLE
Add information page that lists the symlink information for USB cameras

### ISSUE THREAD

**Issue by virtuald** [wpilibsuite/cameraserver#76]
Would make it easier for users to figure out what to put in the 'path' if they didn't want to use the automatic indexed camera access when using multiple cameras.

**Comment by virtuald** [comment]
And while this should be in the docs, I mean at runtime it would be good if you could go to the web server and bring up a page that would show this information for the camera that you're currently looking at.

**Comment by virtuald** [comment]
Also, I have a page on this in the robotpy cscore docs: http://robotpy.readthedocs.io/en/stable/vision/roborio.html#sometimes-the-first-and-second-camera-swap

**Comment by auscompgeek** [comment]
Fixed by wpilibsuite/allwpilib#1519, I think.

**Comment by virtuald** [comment]
So it is.
