### ISSUE TITLE
Add information about USB bandwidth allocation

### ISSUE THREAD

**Issue by virtuald** [wpilibsuite/cameraserver#77]
Maybe a log message saying "device allocation is 40", or something... to help teams debug potential bandwidth issues they may run into.

**Comment by PeterJohnson** [comment]
As far as I've been able to find out so far, it is not possible to do this reliably.  We are planning on adding explicit control over camera start/stop to make hitting the limit more deterministic.

**Comment by PeterJohnson** [comment]
Closing as there doesn't seem to be a way to do this, and we've added explicit control for camera start/stop.
